[조예슬] Mission 4 : 로그인 기능 구현
wecode-bootcamp-korea/35-backend-westagram-3 pull request #14
Opened 2022-07-08 08:05 UTC by eungang3

## 수정 사항 간략한 한줄 요약
- 로그인 구현
		 
## 수정 사항들 자세한 내용
- 이메일로 로그인할 수 있음
- 요청 메시지에 이메일이나 비밀번호 키가 없는 경우 Key Error 400 반환
- db에 존재하지 않는 이메일로 로그인을 시도하는 경우 401 에러 반환
- 이메일과 비밀번호가 일치하지 않는 경우 401 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-08 08:50 UTC, lordmyshepherd requested changes

2022-07-08 08:50 UTC, lordmyshepherd commented on students/yeseul/users/views.py
> +            return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
email 검증과 email, password 검증을 나눠서 할 필요 없이, line 53-56 코드와 line 58-59 코드를 하나로 합치면 좋을 것 같습니다! 

```suggestion
        if not User.objects.filter(email=email, password=password).exists():
            return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
```

2022-07-09 04:14 UTC, eungang3 commented on students/yeseul/users/views.py
> +            return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
코드 합쳐서 다시 push했습니다!

2022-07-11 01:27 UTC, AhnSang0915 commented on students/yeseul/users/views.py
> +            return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
GOOD

2022-07-11 02:28 UTC, kyeongraekim requested changes
안녕하세요 예슬님~ 아래 내용 참고하여 수정사항을 한 번 고려해보세요!~

2022-07-11 02:28 UTC, kyeongraekim commented on students/yeseul/users/urls.py
> +    path('/sign_up', SignUpView.as_view()),
url 에서의 언더바 사용은 지양하는 편입니다. "sign-up" 의 형태처럼 하이픈을 적용하여서 보다 RESTful 한 엔드포인트를 접목 시켜보세요~

2022-07-11 02:28 UTC, kyeongraekim commented on students/yeseul/users/views.py
> +        return JsonResponse({'message' : 'SUCCESS'}, status = 200)
try-catch의 형태를 각 코드블록마다 진행을 해주셨는데 혹시 해당 내용처럼 작성해주신 특별한 이유가 있으실까요?

파이썬으로 작성하는 코드중, (1) 하나의 try 블록 내에 발생가능한 except문을 이어주는 경우가 있고, (2) 반대로 가독성을 위해서 하나의 try 안에 여러개의 발생가능한 에러를 except문의 나열 형태로 진행하는 형태도 있습니다. 

현재 로그인 뷰의 기능은 그 구조가 많이 단순한 형태이고 여러 복문 형태의 try-catah를 사용할 정도의 코드 길이가 아님으로, 가독성에 보다 신경쓴 코드로 전환시켜주시는 것을 권장드립니다~

2022-07-11 03:45 UTC, eungang3 commented on students/yeseul/users/urls.py
> +    path('/sign_up', SignUpView.as_view()),
sign-up으로 수정했습니다!

2022-07-11 03:46 UTC, eungang3 commented on students/yeseul/users/views.py
> +        return JsonResponse({'message' : 'SUCCESS'}, status = 200)
(1)번 목적으로 try-catch 블록을 나누었는데 코멘트 달아주신 것 보고 (2)번으로 수정했습니다~

2022-07-11 05:39 UTC, kyeongraekim requested changes

2022-07-11 05:39 UTC, kyeongraekim commented on students/yeseul/users/views.py
> +        return JsonResponse({'message' : 'SUCCESS'}, status = 200)
가독성을 높일 수 있는 또 하나의 방법은 Try문에서의 코드 기능의 정상적인 흐름과, 에러를 잡는 except문들의 의미론적인 영역구분을 짓는 것 입니다. 해당 리턴 메세지를 52~54번쨰 라인 안에서 실천하였으면 더 코드 진행면에서 깔끔한 논리 흐름이 확보될 것 같네요!

2022-07-11 06:14 UTC, eungang3 commented on students/yeseul/users/views.py
> +        return JsonResponse({'message' : 'SUCCESS'}, status = 200)
성공 시 반환하는 리턴 메세지(60번 라인)를 try문 안에 넣어보았습니다!

2022-07-11 07:35 UTC, lordmyshepherd requested changes

2022-07-11 07:35 UTC, lordmyshepherd commented on students/yeseul/users/views.py
> +                return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
존재 유무만 판단할 때에는 `.exists()`를 사용하는 것이 성능, 가독성 면에서 좋습니다.
```suggestion
            if not User.objects.filter(email=email, password = password).exists():
                return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
```

2022-07-11 07:50 UTC, eungang3 commented on students/yeseul/users/views.py
> +                return JsonResponse({'message' : 'INVALID_USER'}, status = 401)
- exists()로 수정했습니다.
- ObjcetDoesNotExist 에러를 캐치하는 부분은 삭제했습니다.

2022-07-11 08:38 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-11 08:38 UTC, merged