[김민지] Mission 3 : 회원가입기능 구현
wecode-bootcamp-korea/35-backend-westagram-3 pull request #15
Opened 2022-07-08 08:40 UTC by enddl3224

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 기능 추가
		 
## 수정 사항들 자세한 내용
- 사용자 이름, 이메일, 비밀번호, 연락처 기입 가능
- 위의 정보 중 1개라도 미기입한 경우 에러발생
- 이메일 기입 시 @와 . 가 필수로 포함되어야 함
- 비밀번호는 문자, 숫자, 특수문자의 조합인 8자리 이상이어야 함
- 위의 조건 지켜지지 않을 경우 에러발생

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-08 08:53 UTC, lordmyshepherd requested changes

2022-07-08 08:53 UTC, lordmyshepherd commented on students/minji/users/views.py
> +            emailForm = re.compile('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

다른 곳(예를 들어서 로그인 기능)에서 이메일 검증이 필요한 경우 해당 정규표현식을 재사용할 수 있도록 class UserView 밖에 선언해주세요-!
```python
REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
```

2022-07-08 08:53 UTC, lordmyshepherd commented on students/minji/users/views.py
> +                    return JsonResponse({"message" : "Email Duplicate"}, status=400)
불필요하게 반복문을 돌릴필요 없이, filter() 함수와 exists() 함수를 사용해서 구현해보시면 좋을 것 같습니다-!

2022-07-08 11:17 UTC, enddl3224 commented on students/minji/users/views.py
> +                    return JsonResponse({"message" : "Email Duplicate"}, status=400)
넵 함수 이용해서 작성해보겠습니다!

2022-07-11 01:33 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-07-11 01:33 UTC, merged