[김민지] Mission 4 : 로그인 기능 구현
wecode-bootcamp-korea/35-backend-westagram-3 pull request #16
Opened 2022-07-09 05:48 UTC by enddl3224

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능 추가
		 
## 수정 사항들 자세한 내용
- 회원가입이 된 유저만 로그인 가능
- 이메일, 비밀번호 잘못됐을 경우 INVALID_USER 반환
- 로그인 성공 시 SUCCESS 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-09 07:08 UTC, ooooo5h commented on students/minji/users/views.py
> +            matchEmail = User.objects.filter(email = data['email'])
westudy > westagram kickoff > **wecode python coding convention**에 따르면
- 일반적으로 [변수/클래스]는 이름이 "명사"로 이루어지며 [함수]는 "동사"입니다.
- 파이썬에서는 클래스의 이름을 제외하고 일반적으로 _를 사용해서 단어를 구분합니다.

라고 되어있더라구요 민지님! 
matchEmail은 동사로 시작하고, 단어의 연결도 대문자로 되어있네요. 민지님이 더 좋게 개선하실 수 있을 것 같습니다.😄

2022-07-09 12:27 UTC, enddl3224 commented on students/minji/users/views.py
> +            matchEmail = User.objects.filter(email = data['email'])
좋은 정보 감사합니다!! 참고해서 수정하도록 하겠습니다.😃

2022-07-11 02:40 UTC, kyeongraekim requested changes

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +            if not re.match(REGEX_EMAIL, data['email']):
data['email'] 은 현 시점에서 말고도 아래에서 2번 이상 활용되는 값처럼 보여지네요!~ 
15번째 라인 즈음에 email = data['email'] 정도로 변수에 담아서 아래 코드에서의 재사용성을 실현시켜 보세요~

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +                return JsonResponse({"message" : "Email Error"}, status=400)
클라이언트가 확인하는 리턴메세지는 "Invalid User" 정도의 포괄적인 메세지여도 충분할 것으로 보여집니다~
굳이 디테일한 내용, 즉 어떤 부분에서 에러가 난 것인지를 보안상의 이유로 일부러 밝히지 않는 것이지요!~

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +                return JsonResponse({"message" : "Email Duplicate"}, status=400)
리턴 메세지의 영문법도 디테일하게 신경쓸 수 있는 섬세함을 보여주세요!~ 
Email Duplicated Entry 정도로 수정하면 좋을 것 같네요!~

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +                return JsonResponse({"message" : "PW Error"}, status=400)
이 부분도 Invalid User 정도가 괜찮겠네요!~

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +            matchEmail = User.objects.filter(email = data['email'])
혹시 이부분은 수정이 반영된 것일까요? 동기분께서 잘 짚어주신 부분 반영 부탁드립니다!~

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +            if User.objects.filter(email = data['email']) and data['password']==matchEmail[0].password:
filter method 안에서  comma 를 사용하시면 위 내용을 Django Queryset ORM 기능을 십분 활용하여 구현시킬 수 있을것 같네요!~
filter(A, B) 의 형태로 바꾸어 보세요~

2022-07-11 02:40 UTC, kyeongraekim commented on students/minji/users/views.py
> +            else:
else로의 추가 분기가 이곳에서 꼭 필요할까요? 위의 if문이 발동이 되지 않으면 추가 분기 없이도 최하위단의 리턴 메세지는 실행될 것이라는 것을 염두해서 수정해보세요~

2022-07-11 02:41 UTC, kyeongraekim commented on students/minji/users/views.py
> +            else:
SignUp 부분도 같이 올라와있는 부분 한 번 수정 언급해드렸어요~ Mission4 까지는 수정 같이 반영해주시고~ 그 이후 다음부터 로그인 기능에만 국한되어서 올려주시는 것을 잊지말아주세요!~

2022-07-11 05:51 UTC, enddl3224 commented on students/minji/users/views.py
> +            matchEmail = User.objects.filter(email = data['email'])
참고해서 수정하였지만 Django Queryset ORM 기능 중 filter(A,B)을 활용하다보니 변수 지정이 의미가 없어져 삭제하였습니다!

2022-07-11 05:53 UTC, enddl3224 commented on students/minji/users/views.py
> +            else:
넵 다음부터 해당기능만 업로드하겠습니다 감사합니다!

2022-07-11 07:36 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-07-11 07:36 UTC, merged