[조예슬] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/35-backend-westagram-3 pull request #20
Opened 2022-07-11 06:39 UTC by eungang3

## 수정 사항 간략한 한줄 요약
- 회원가입 시 비밀번호에 암호화 적용
		 
## 수정 사항들 자세한 내용
- 클라이언트에서 전달받은 비밀번호를 bcrypt로 해싱
- 해시값 DB에 저장

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-11 08:26 UTC, willy99624 commented
좋습니다!

2022-07-12 01:29 UTC, kyeongraekim requested changes

2022-07-12 01:29 UTC, kyeongraekim commented on students/yeseul/users/views.py
> +        # 비밀번호 암호화
코드상에서 의미를 충분히 알 수 있는 내용은 주석으로 부연설명할 필요가 없으십니다~ 삭제해주셔도 무방해보이네요!~

2022-07-12 01:29 UTC, kyeongraekim commented on students/yeseul/users/views.py
> +            password     = hashed_password.decode(),
뒤에 붙는 ".decode()" 메소드를 37번 라인에서 정의한 미리 decode를 한 이후에 이곳에서 value로서 활용 될 수 있게 해도 괜찮을 것 같네요!~ 
그 이유는 create()를 통해서 발동되는 ORM queryset 선에서의 행동과, 데이터베이스에 넣기 위해서 암호화된 비밀번호를 decode하는 행동을 의미적으로 분리시키기 위함입니다. 추가 이점으로 혹시나 비밀번호 암호화 중 문제가 생기면 37번 라인에서의 암호화만의 문제로서 직관적으로 파악할 수 있게 되겠네요~

```python
        hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode()

        User.objects.create(
            name         = name,
            email        = email,
            password     = hashed_password
...
)

2022-07-12 01:37 UTC, eungang3 commented on students/yeseul/users/views.py
> +        # 비밀번호 암호화
주석 삭제했습니다!

2022-07-12 01:37 UTC, eungang3 commented on students/yeseul/users/views.py
> +            password     = hashed_password.decode(),
decode 메소드 분리했습니다!

2022-07-12 01:43 UTC, kyeongraekim commented
넵 코드 전반에 걸쳐져있는 주석 처리 내용도 함꼐 삭제해주세요!~ 기타 동료 개발자들에게 있어서 코드독해선에서 충분히 의미파악이 가능하며 굳이 별도의 설명이 필요한 주석의 내용처럼은 보이지 않네요!~

2022-07-12 01:47 UTC, eungang3 commented
주석 삭제했습니다!

2022-07-12 01:48 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-12 01:48 UTC, merged