[이원재] Mission 6 : 로그인 JWT 발급
wecode-bootcamp-korea/35-backend-westagram-3 pull request #21
Opened 2022-07-11 07:52 UTC by willy99624

## 수정 사항 간략한 한줄 요약
- 로그인 JWT 발급

## 수정 사항들 자세한 내용
- 로그인 JWT 발급

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-11 08:17 UTC, eungang3 commented
LGTM!

2022-07-12 01:33 UTC, kyeongraekim requested changes

2022-07-12 01:33 UTC, kyeongraekim commented on students/wonjae/users/views.py
> +
해당 부분의 키에러 발생 가능성을 잡고있는 에러처리는 보이지가 않네요!~

2022-07-12 01:33 UTC, kyeongraekim commented on students/wonjae/users/views.py
> +            token = jwt.encode({"user_id":User.objects.get(email=email).id}, SECRET_KEY, algorithm="HS256")
- 모두가 공공연히 볼 수 있는 깃허브 코드 선에서 구체적인 algorithm 값을 파악할 수 있게 하면 보안상의 취약점을 드러낼 수 있습니다.
따라서 환경변수안에 넣어서 관리해주세요!~

- token에 넣는 id 값은 구체적인 'user_id' 라는 key로 주는 것 보다 가장 포괄적인 단어인 'id' 라는 내용으로 수정해주세요~ 클라이언트 측에서 직관적으로 유저의 정보를 파악할 수 있는 단어의 사용은 지양해주셔야 합니다~

2022-07-12 06:44 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-12 06:44 UTC, merged