[안상현] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/35-backend-westagram-3 pull request #22
Opened 2022-07-11 08:23 UTC by AhnSang0915

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 비밀번호 암호화 작업 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 비밀번호 암호화 추가 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-11 08:27 UTC, willy99624 commented
좋습니다!

2022-07-12 01:36 UTC, kyeongraekim requested changes

2022-07-12 01:36 UTC, kyeongraekim commented on students/sanghyun/users/views.py
>                  mobile_number = data['mobile_number']
이 곳은 이미 19~21번 째라인에서 올바르게 변수에 넣어준 value 값들을 재사용해주시면 될 것 같네요! 불필요한 매핑 연산이 계속 진행되고 있습니다~ mobile_number 의 존재여부도 미리부터 파악하여서 이후의 코드를 불필요하게 훑지않아도 되게 22번째 라인에 추가로 모든 키값들이 잘 들어왔는지 변수에 지정해주세요~

2022-07-12 01:36 UTC, kyeongraekim commented on students/sanghyun/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
21번째 라인과 19번째 라인의 password는 중복되어 보이네요 둘 중 하나를 제거해주셔도 무방해보입니다~

2022-07-12 07:00 UTC, kyeongraekim requested changes

2022-07-12 07:00 UTC, kyeongraekim commented on students/sanghyun/users/views.py
해당 부분은 클라이언트/프론트엔드가 직접 사용자에게 보내주는 리턴 메세지의 경우에 필요한 디테일한 리턴 메세지같아 보이네요~ invalid_user 정도로 외부의 요소 확인을 최소화할 수 있게 변경해주시면 좋을 것 같네요!

2022-07-12 07:31 UTC, kyeongraekim approved these changes

2022-07-12 07:31 UTC, kyeongraekim commented on students/sanghyun/users/views.py
> +
현재 올려주신 부분은 Mission 6에 해당되는 내용이네요!~ 추후에 리뷰 드리겠습니다!

2022-07-12 07:33 UTC, kyeongraekim commented on students/sanghyun/users/views.py
> +
추가 참고사항으로 실무에 나가시면 내가 의도한 기능에 대한 내용만 깃헙에 푸시해주셔야 합니다. 그러한 내용의 사전연습을 각 미션별 분리 푸쉬로 Westagram 과제에서 연습중임으로 다음부터는 다른 Mission에 해당되는 내용은 같이 동봉되어서 올라오지 않게 유의해주세요!~

2022-07-12 07:33 UTC, merged