[안상현] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/35-backend-westagram-3 pull request #25
Opened 2022-07-12 07:46 UTC by AhnSang0915

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 JWT 발급 메소드 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 패스워드 인증 완료시 id를 포함한 JWT발급
- 발급한 JWT를 응답의 데이터로 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-12 07:51 UTC, willy99624 commented
email        = data['email']
password = data['password']

이렇게 빼는게 좋을것 같습니다!

2022-07-12 08:02 UTC, AhnSang0915 commented
> 

수정했습니다. 감사합니다~

2022-07-13 01:35 UTC, kyeongraekim requested changes

2022-07-13 01:35 UTC, kyeongraekim commented on students/sanghyun/users/views.py
> +            user = User.objects.get(email=email)
해당 코드 라인에서 Model.DoesNotExist 에러가 날 가능성이 보이네요~ 에러핸들링으로 처리 진행해주세요

2022-07-13 01:36 UTC, kyeongraekim commented
컨플릭트도 같이 해결해주셔야하는데 혹시 잘 해결이 되지 않으면 코멘트로 남겨주세요~

2022-07-13 04:38 UTC, AhnSang0915 commented on students/sanghyun/users/views.py
> +            user = User.objects.get(email=email)
Model.DoesNotExist 에러추가 했습니다.

2022-07-13 04:44 UTC, AhnSang0915 commented
수정한 내용이 잘 push되는데 conflict에러를 어디서 확인할 수 있나요?

2022-07-13 04:48 UTC, kyeongraekim commented
> 수정한 내용이 잘 push되는데 conflict에러를 어디서 확인할 수 있나요?

작성하신 reply 바로아래 conflicting files라고 되어있는 부분 확인해보세요~

2022-07-13 05:24 UTC, AhnSang0915 commented
> > 수정한 내용이 잘 push되는데 conflict에러를 어디서 확인할 수 있나요?
> 
> 현재 reply 바로 아래로 스크롤 다운 해주시고 conflicting files라고 되어있는 부분 확인해보세요~ 푸시의 성공여부와 추후의 머지의 성공여부는 다른 것을 의미하니 참고해주세요!~

깃헙 공식문서 보고 수정했는데 이렇게 하는게 맞는지 모르겠습니다. 커맨드라인에서 안하고 웹에서 수정했는데 확인부탁 드립니다.

2022-07-13 06:12 UTC, kyeongraekim commented
> > > 수정한 내용이 잘 push되는데 conflict에러를 어디서 확인할 수 있나요?
> > 
> > 
> > 현재 reply 바로 아래로 스크롤 다운 해주시고 conflicting files라고 되어있는 부분 확인해보세요~ 푸시의 성공여부와 추후의 머지의 성공여부는 다른 것을 의미하니 참고해주세요!~
> 
> 깃헙 공식문서 보고 수정했는데 이렇게 하는게 맞는지 모르겠습니다. 커맨드라인에서 안하고 웹에서 수정했는데 확인부탁 드립니다.

기본적으로는 로컬 커맨드 라인에서 해결하는 법을 선이해하고 웹에서 해결하는 법을 적용하시면 좋습니다~ 추후에 관련해서 찾아뵐게요~

2022-07-13 06:41 UTC, AhnSang0915 commented
> > > > 수정한 내용이 잘 push되는데 conflict에러를 어디서 확인할 수 있나요?
> > > 
> > > 
> > > 현재 reply 바로 아래로 스크롤 다운 해주시고 conflicting files라고 되어있는 부분 확인해보세요~ 푸시의 성공여부와 추후의 머지의 성공여부는 다른 것을 의미하니 참고해주세요!~
> > 
> > 
> > 깃헙 공식문서 보고 수정했는데 이렇게 하는게 맞는지 모르겠습니다. 커맨드라인에서 안하고 웹에서 수정했는데 확인부탁 드립니다.
> 
> 기본적으로는 로컬 커맨드 라인에서 해결하는 법을 선이해하고 웹에서 해결하는 법을 적용하시면 좋습니다~ 추후에 관련해서 찾아뵐게요~

넵!

2022-07-14 04:20 UTC, kyeongraekim requested changes

2022-07-14 04:20 UTC, kyeongraekim commented on students/sanghyun/users/views.py
> +            user = User.objects.get(email=email)
email 이라는 변수가 그 어디에도 선언이 되어있지 않는데 변수로서 활용되고 있네요~ 중간에 논리흐름이 끊겨보이는데,  해당 코드가 혹시 잘 돌아갔는지 스크린샷 찍어서 같이 올려주세요!~

2022-07-14 05:45 UTC, AhnSang0915 commented on students/sanghyun/users/views.py
> +            user = User.objects.get(email=email)
제생각엔 conflict 해결할때 변수까지 지워버린거 같아요 .. 내용 수정해서 강제 푸쉬 했습니다.

2022-07-14 08:15 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-14 08:15 UTC, merged