[김민지] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/35-backend-westagram-3 pull request #26
Opened 2022-07-12 12:24 UTC by enddl3224

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 암호화된 비밀번호 토큰 발급
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 암호화된 비밀번호 DB에서 확인
- 사용자의 id를 담아 jwt 발급

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-12 12:27 UTC, willy99624 commented
암호 알고리즘을 환경변수로 세팅해주시는게 좋을거 같아요~

2022-07-12 12:36 UTC, enddl3224 commented
수정완료했습니다! 알고리즘은 숨기는 게 좋다는 정보 감사드려요!

2022-07-13 01:33 UTC, kyeongraekim requested changes

2022-07-13 01:33 UTC, kyeongraekim commented on students/minji/users/views.py
> +            return JsonResponse({"message": encoded_jwt}, status = 200)
추후에 프론트/클라이언트 측에서 받은 리턴메세지를 토대로, 명확한 키값을 이용해 이후의 본인들의 로직에서 활용할 수 있게 message라는 Key보다 token, access_token 정도로 바꾸어주세요~

2022-07-13 01:33 UTC, kyeongraekim commented on students/minji/users/views.py
> +            encoded_jwt = jwt.encode({'id':User.objects.get(email=email).id},'secret',algorithm=ALGORITHM)
jwt의 비밀 키 부분이 'secret'이라는 문자열로 하드 코딩 되어 있네요~ 깃헙에 푸시되어 올라오는 상용화된 코드에서 하드코딩은 최대한 지양해주셔야 합니다. 환경 변수로 관리하시는 SECRET_KEY를 호출해서 사용해주세요

2022-07-13 04:32 UTC, enddl3224 commented on students/minji/users/views.py
> +            encoded_jwt = jwt.encode({'id':User.objects.get(email=email).id},'secret',algorithm=ALGORITHM)
시크릿도 환경변수로 관리해 줘야 하는군요
방금 수정해서 업로드했습니다!

2022-07-13 04:47 UTC, kyeongraekim requested changes

2022-07-13 04:47 UTC, kyeongraekim commented on students/minji/users/views.py
> +            encoded_jwt = jwt.encode({'id':User.objects.get(email=email).id},SECRET_KEY,algorithm=ALGORITHM)
jwt token 발급이 아래 위치한 if 문들 이후에 위치해야 될 것 같아보이네요! 파이썬의 코드흐름은 위에서 아래로 진행된다는 점 잊지 말아주세요!~ 이상적인 로직으로, 요청에 대한 전반적인 유효성이 잘 판단된 이후에 token을 생성하고 반환하는 형식으로 진행해주세요~

2022-07-13 05:46 UTC, kyeongraekim requested changes

2022-07-13 05:46 UTC, kyeongraekim commented on students/minji/users/views.py
> +                return JsonResponse({"MESSAGE": "SUCCESS"}, status = 200)
해당 코드의 의미가 어떤것을 의미하시는지 코멘트로 남겨주실 수 잇으실까요? 전체 로직흐름상 불필요한 부분 처럼 보여지네요~
해당 if문에 걸려서 로직이 흘러가게되면 그냥 Success메세지만을 던지고 해당 post함수는 종료되게 됩니다. 아래 토큰 리턴메세지 까지도 접근이 힘든 상황입니다. 
그런데 그보다 앞서서, 암호화된 비밀번호에 대한 내용으로 리팩토링하는 부분이니 그저 request 요청 객체에서 함께 들어온 password와 db상 암호화된 password를 비교해서 맞는 유저 계정은 없겠지요. 혹시 미션 4와 하이브리도로 작업해주신 것이라면 해당 내용은 삭제하시고 암호화된 계정에 대한 로그인 기능만 코드로서 남겨주세요~

2022-07-13 11:52 UTC, enddl3224 commented on students/minji/users/views.py
> +                return JsonResponse({"MESSAGE": "SUCCESS"}, status = 200)
DB에 있는 email과 password의 존재만 확인한다면 사용자1의 email과 사용자2의 password로 로그인이 가능하기 때문에 이러한 일을 방지하려고 넣은 코드였습니다. 그래서 DB에 저장되어있는 email과 클라이언트가 입력한 email 값이 같으면서 password가 같을 경우 SUCCESS를 출력하라는 코드를 넣었었습니다..!
코드를 다시 확인해보니 DB에 저장되어 있는 password는 encode 된 값이고 클라이언트가 넣는 password 값은 encode 되지 않은 값이라 60번줄의 if문이 실행되지 않는다는 것을 알았습니다!
수정하여 다시 push하도록 하겠습니다

2022-07-14 04:15 UTC, kyeongraekim approved these changes

2022-07-14 04:18 UTC, kyeongraekim requested changes

2022-07-14 04:18 UTC, kyeongraekim commented on students/minji/users/views.py
> +        password = data['password']
try 문에 해당 내용을 넣어야 KeyError에 대한 핸들링이 가능하겠네요! 그 이유에 대해서 한 번 곰곰히 생각해보세요~
만일 그렇지 않다면 500 에러가 나올 텐데 500 에러 + 서버의 셧다운은 백엔드가 최대한 지양해야되는 상황입니다!~

2022-07-14 04:18 UTC, kyeongraekim commented on students/minji/users/views.py
> +from my_settings      import ALGORITHM, SECRET_KEY
해당 내용을 my_settings에서 직접 긁어오는 것이 아닌, django.conf.settings 에서 불러오는 방식으로 변경에 도전해보세요!~
my_settings에 대한 의존성을 views.py에서 분리시키는 것이 주된 목적입니다~

2022-07-14 08:15 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-14 08:15 UTC, merged

2022-07-14 10:21 UTC, enddl3224 commented on students/minji/users/views.py
> +        password = data['password']
try문에서 email과 password가 잘 들어왔는지 확인을 한 후 잘 들어오지 않을 경우 KeyError를 반환해야하는데 확인하는 코드가 try문 밖에 있기 때문에 except문에 해당하지 않아서 500에러가 나온다! 라고 이해했는데 틀렸다면 다시 생각해보겠습니다